version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: tekoa
      POSTGRES_PASSWORD: tekoa
      POSTGRES_DB: tekoa
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      DATABASE_URL: postgres://tekoa:tekoa@db:5432/tekoa
      PORT: 4000
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
